### ISSUE TITLE
Add more use cases to docs README

### ISSUE THREAD

**Issue by lilic** [JESWINKNINAN/kube-anchor#3]
Great idea for the project, I can see a few more use cases being added here.

Use cases I see where this can be useful is for large companies that cannot communicate to everyone at once and want to lock production
- During Kubernetes upgrade, to prevent any workload updates
- During incidents or outages
- During planned maintaince of infrastructure for example

Just a couple of use cases I can see. Great stuff otherwise! 🎉

**Comment by RiRa12621** [comment]
This probably also makes sense in a multi-tenant environment where certain namespaces should be immutable

**Comment by jeswinkninan** [comment]
@lilic Thank you for the feedback, I will add a separate section in readme with the usecases which you have shared. 
@RiRa12621 Thank you, Will add this as well.

**Comment by jeswinkninan** [comment]
@lilic @RiRa12621 Based on your comments, I have added the usecases as mentioned.
